[formatter.nix]
command = "nix"
options = [
  "fmt",
]
includes = [
  "*.nix",
]

[formatter.py]
command = "black"
options = [
  "--line-length=79",
]
includes = [
  "*.py",
]

[formatter.py-lint]
command = "ruff"
options = [
  "check",
]
includes = [
  "*.py",
]
